### ISSUE TITLE
Handle multiple manifests design

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-lib#10]
The original issue from @mscottford is below.

>Scenario:
>A project that is using a Maven and NPM. The libyear datat should be computed from both of them combined.

I, @mrbiggred, changed this issue to a design issue to discuss the format we want the data for multiple manifests.   One big libyear number is good  but my guess is we should also return data on a per project and possibly per manifest file.  Some examples to consider:

- A .NET solution with multiple projects.  Only uses NuGet dependencies.
- A .NET solution with multiple web projects.  Uses NuGet and NPM dependencies.
- A Rails project that has a Gems and NPM packages.
- Calculate the libyear for a single manifest file.  Either as the file is now and possibly over time.
- Calculate the libyear for all the manifests in a given folder.
- Any other good examples we should add?

Some ways to break down the data returned to the consumer:

- A single libyear for the entire repo.
- A libyear per manifest file.
- A libyear per folder.
- A libyear per manifest type (e.g. NuGet vs NPM).
- Any other examples?

This issue is just for discussion design ideas.  The design decisions will be implemented in other cases.

**Comment by mscottford** [comment]
I see this as being hierarchical. 

A single logical application may be composed out of many source code repositories, and a single source code repository may contain multiple dependency manifests.

I'd like for us to be able to report about the health of the entire application, in addition to its sub-components. Some of this was sketched out the reports that BLDR prototyped for us for the freshli-web project.

Essentially, we'd just need to keep track of the relationships between the different pieces of data. The libyear metric is computed per package, so to get the total libyear for a manifest, we'd just need to sum those package libyears. If a repository has multiple manifests, then the total libyear for that repository would be the sum of the total libyear for each manifest. If an application has multiple repositories, then the total libyear for the application would be the sum of the total libyear from each repository. The relationship would be similar for other aggregate calculations (such as max). We'd need to take a slightly different approach if we wanted to compute some other statistical indicators, such as average or standard deviation. For those,  we'd need all of the individual package libyear calculations for each clustering. But even then, we'd just get that data from the relationship of Application -> Repository -> Manifest -> Package.

**Comment by mrbiggred** [comment]
This design issue spawned #252 so now Freshli parses multiple manifest files.  Leaving this design issue open so we can discuss how Freshli should return the data from multiple manifests.

**Comment by mscottford** [comment]
This responsibility has been moved to Freshli-CLI. Multiple dependencies are detected by language-specific agents, and each manifest is processed.
