### ISSUE TITLE
Acceptance Test Fails in Windows Development Environment

### ISSUE THREAD

**Issue by dan-hein** [corgibytes/freshli-lib#205]
### Overview
The Acceptance Test **UnsupportedGitRepository** fails in the Windows development environment. It appears that this is caused by the file path and extension violating the 260 character Windows constraint. Windows 10 has contingencies to get around this issue, but the dependency **LibGit2Sharp v0.26.2** does not currently honor this setting.

### Proposed Solution
This is a known [issue](https://github.com/libgit2/libgit2sharp/issues/1805) in LibGit2Sharp. Once the fix for this is reviewed and merged, a few additional steps will be required on a Windows machine.

1. Enable long file paths within git configuration as seen [here.](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)
`git config --system core.longpaths true`
2. Edit Windows Registry to allow for Long Paths as seen [here.](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/)
`Set Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled to 1`
3. Restart Machine.

There may also be other alternatives that I am not aware of, but these are the results based on my current research.

### Temporary Work-Around
Work on Freshli Development in a Linux or Mac Environment.

### Environment
Windows 10 x64
Rider and Visual Studio Community 2019
.NetCore SDK 3.1.301

### Screenshots
![Failed Test -2](https://user-images.githubusercontent.com/5385329/103575865-eb524e00-4e97-11eb-9a3f-44592f2e539b.PNG)
![Failed Test -3](https://user-images.githubusercontent.com/5385329/103575884-f1e0c580-4e97-11eb-85ac-75da30414419.PNG)

**Comment by steverichey** [comment]
For what it's worth, I'm not seeing this issue in Windows 11. It's possible this is thanks to using LibGit2Sharp version `0.27.0-preview-0182`.

**Comment by mscottford** [comment]
Let's go ahead and close it then. :)
