### ISSUE TITLE
Determine the libyear for single manifest file

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-lib#251]
Freshli should be able to determine the lib year for a single manifest file as it stands.  No mapping the manifest file over time, just the libyear for the current file as it is.  Something like:

```dotnet
var libCalc= new LibYearCalculator();
libYear = libCalc.calc(pathToManifestFile);
```

Not sure if theLibYearCalculator is the best place or not.  I'm sure calculating the libyear from a file is already being done I would just like to expose it as a public interface.

The design decisions from #10 (Handle multiple manifests design) will likely impact this issue.

**Comment by mscottford** [comment]
[Freshli-CLI #234](https://github.com/corgibytes/freshli-cli/issues/234) has been created in response to this request.
