### ISSUE TITLE
Fix multiple CodeClimate Freshli projects

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-lib#253]
For some reason there are two Freshli-Lib CodeClimate projects:

https://codeclimate.com/github/corgibytes/freshli

https://codeclimate.com/repos/601c1f18f9414200c900094b

The second one has the code coverage results but the first one is what is shown when you click on the CodeClimate details in a PR.  Also the second one is not publicly viewable.  We need to figure out why there are two Freshli Code Climate projects and figure out how the merge them.

**Comment by mscottford** [comment]
Once #286 is merged in then we can delete the private project.
