### ISSUE TITLE
Rename this repo and/or C# namespace

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-lib#259]
We have been discussing users coming to this repo to use Freshli when most users will want Freshli CLI or the website.  One possible solution is to rename this repo to FreshliLib or something similar.  

We have also discussed if we should rename the NuGet package and/or the C# namespace.  For example instead of "Freshli-0.3.0" as the NuGet package it would be "FreshliLib-0.3.0".  Similar the C# namespace would change from:

```csharp
using Freshli;
```

To:

```csharp
using Freshli.Lib;
```

The one thing we all agree on is changing the repo name and adding something to the ReadMe to redirect users to the CLI/Website.  Not sure about renaming the package or C# namespace yet.  Thoughts @mscottford, @dfar-io, and anyone else?

**Comment by mrbiggred** [comment]
@dfar-io and @mscottford I think we should put "Corgibytes" in the namespace so it looks like:

```csharp
using Corgibytes.Freshli.Lib;
```

I'm not sure if we want to rename all the files.  If we do they would look like:

```
Corgibytes.Freshli.sln
Corgibytes.Freshli.Lib (directory)
    Corgibytes.Freshli.Lib.csproj
...
```

Thoughts?

**Comment by mscottford** [comment]
I like that idea.

M. Scott Ford
Co-Founder & CEO
Corgibytes, LLC
804.596.2375 x701
pronouns: he/him
scott@corgibytes.com
https://corgibytes.com ( https://corgibytes.com/ )

Have you read our First Round Review ( http://firstround.com/review/forget-technical-debt-heres-how-to-build-technical-wealth/ ) article about paying off technical debt?

Love refactoring and TDD? Join us at LegacyCode.Rocks ( http://LegacyCode.Rocks ) for virtual meetups, podcasts, and more.

Sent via Superhuman ( https://sprh.mn/?vip=scott@corgibytes.com )

**Comment by mfcorgi** [comment]
I renamed the repo to freshli-lib and created a PR with the workspace rename.
