### ISSUE TITLE
Version not correctly incremented when merging tag from release to main

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli-lib#268]
When the [v0.3.0](https://github.com/corgibytes/freshli/releases/tag/v0.3.0) tag was created on the release-0.3 branch and merged back to "main" the version calcuated by GitVersion should have incremetned to 0.4.0 but instead was stuck at 0.3.0.  For an example see the [log](https://pipelines.actions.githubusercontent.com/GNP63J2O2GRc9JkPzqtooBUV1IcK8fLrcev4o72BLkMaTZN9ZO/_apis/pipelines/1/runs/1851/signedlogcontent/3?urlExpires=2021-03-02T18%3A32%3A13.4573525Z&urlSigningMethod=HMACV1&urlSignature=UgWTg6QZOKt2pexU12Yh0zRBNzfaDIrnGs1Bos1Py2E%3D) for [this](https://github.com/corgibytes/freshli/runs/2015749784) build.

Part of the log that is interesting:

```
  INFO [03/02/21 18:13:03:71] Begin: Calculating base versions
    INFO [03/02/21 18:13:03:75] Fallback base version: 0.1.0 with commit count source 5bf0482ec82ea56c45717fb52cc60c5f42450823
    INFO [03/02/21 18:13:03:86] Git tag 'v0.2.0': 0.2.0 with commit count source 4d2dd230a0bbe07f4de9b3bc98c65ebd789ab6dd
    INFO [03/02/21 18:13:03:90] Found multiple base versions which will produce the same SemVer (0.3.0), taking oldest source for commit counting (Git tag 'v0.2.0')
    INFO [03/02/21 18:13:03:90] Base version used: Git tag 'v0.2.0': 0.2.0 with commit count source 4d2dd230a0bbe07f4de9b3bc98c65ebd789ab6dd
  INFO [03/02/21 18:13:03:90] End: Calculating base versions (Took: 185.31ms)
```

Info on configuration GitVersion can be found [here](https://gitversion.net/docs/reference/configuration).

**Comment by mrbiggred** [comment]
I figured out the problem.  It is because the release branch was merged using Squash.  When squashed tags are lost and not merged.  So the question is how to deal with this.  Do have a special case for merging from release to main?  Do we stop squashing altogether?  Some other option?

**Comment by dfar-io** [comment]
What if we were to merge the tag created (create a Github Action that automatically merges tags into `main`) and see if that'll increment the version correctly? If so we wouldn't have to worry about handling merges back into main for release changes.

I'd still like to squash PRs (makes for much cleaner commit history) but don't want to have to remember not to squash the release branch.

**Comment by mrbiggred** [comment]
Discussed with @mscottford and decided to disable squash merging.  So future merges will include tags.  To fix this issue I created a new PR to merge, not squash, the `release-0.3` branch changes to `main`.
